# Generated by Django 5.1.1 on 2024-09-16 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_ordencompra_detalleorden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenitem',
            name='orden',
        ),
        migrations.RemoveField(
            model_name='ordenitem',
            name='producto',
        ),
        migrations.DeleteModel(
            name='Orden',
        ),
        migrations.DeleteModel(
            name='OrdenItem',
        ),
    ]
